### ISSUE TITLE
Savings percentage is wrong

### ISSUE THREAD

**Issue by stopsatgreen** [1000ch/webponize#7]
The percentage shown is not the _Savings_ but the size of the file compared to the original. For example:

> Before 1,399,551 After 269,176 Savings 19.2%

The _After_ is 19.2% the size of the original, so the _Savings_ number should be the inverse: 80.8%

![screen shot 2015-06-09 at 10 33 18](https://cloud.githubusercontent.com/assets/98774/8054769/08d576fa-0e93-11e5-9f0b-294abfd145c9.png)

**Comment by 1000ch** [comment]
I'll fix it soon. Thank you :+1:

**Comment by 1000ch** [comment]
@stopsatgreen This is fixed. Please try `v1.1.5` :)

**Comment by stopsatgreen** [comment]
That was **fast**! Problem solved, thanks.
